---
- hosts: others:kube
  become: true
  vars_files:
    - vault.yml
  vars:
    - ipaclient_mkhomedir: true
    - ipaadmin_principal: admin
    - ipaadmin_password: '{{ ipa_admin_pass }}'
    - ipaclient_servers: idm.lab.endorlan.net
    - ipasssd_enable_dns_updates: true

  collections:
    - freeipa.ansible_freeipa

  tasks:
    - import_role:
        name: ipaclient

    - name: change dns to IPA
      lineinfile:
        path: /etc/network/interfaces.d/50-cloud-init
        regexp: 'dns-nameservers'
        line: '    dns-nameservers 10.0.0.9'
        state: present

    - name: change dns-search to lab
      lineinfile:
        path: /etc/network/interfaces.d/50-cloud-init
        regexp: 'dns-search'
        line: '    dns-search lab.endorlan.net'
        state: present
      register: dns_updated

    - name: reboot to update
      ansible.builtin.reboot:
        reboot_timeout: 180
      when: dns_updated.changed
