---
- hosts: kube
  become: true
  vars:
    kubernetes_allow_pods_on_master: true
    kubernetes_pod_network:
      cni: 'flannel'
      cidr: '10.244.0.0/16'

  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
