---
- hosts: all
  become: true
  vars_files:
    - vault.yml
    - defaults/main.yml
    - vars/main.yml

  roles:
    - geerlingguy.security

  tasks:
# - import_playbook: additional_playbooks/nginx_proxy.yml
# - import_playbook: database_setup.yml
# - import_playbook: nameserver_setup.yml
# - import_playbook: additional_playbooks/gitlab_install.yml
- import_playbook: additional_playbooks/kube_install.yml