---
- hosts: all
  become: true
  vars_files:
    - vault.yml
    - defaults/main.yml
    - vars/main.yml

  roles:
    - geerlingguy.security

  tasks:
# - import_playbook: prov_vms.yml
# - import_playbook: nginx_proxy.yml
# - import_playbook: database_setup.yml
# - import_playbook: nameserver_setup.yml
# - import_playbook: gitlab_install.yml
- import_playbook: kube_install.yml