---
domains:
  git:
    - url: git.endorlan.net
      extra: |
        location / {
          client_max_body_size 0;
          gzip off;

          ## https://github.com/gitlabhq/gitlabhq/issues/694
          ## Some requests take more than 30 seconds.
          proxy_read_timeout      300;
          proxy_connect_timeout   300;
          proxy_redirect          off;

          proxy_http_version 1.1;

          proxy_set_header    Host                $http_host;
          proxy_set_header    X-Real-IP           $remote_addr;
          proxy_set_header    X-Forwarded-Ssl     on;
          proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
          proxy_set_header    X-Forwarded-Proto   $scheme;
          proxy_pass http://gitlab-workhorse;
        }

  root_lan:
    - url: endorlan.net
      extra: |
        location / {
          root /var/www/static_web/index.html
        }
        
  root_ext:
    - url: endorsystems.com
      extra: |
        location / {
          root /var/www/static_web/index.html
        }
